/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.developer.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Score extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5790610435402601586L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Score\",\"namespace\":\"io.confluent.developer.avro\",\"fields\":[{\"name\":\"Username\",\"type\":\"string\"},{\"name\":\"Location\",\"type\":\"string\"},{\"name\":\"Score\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Score> ENCODER =
      new BinaryMessageEncoder<Score>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Score> DECODER =
      new BinaryMessageDecoder<Score>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Score> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Score> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Score> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Score>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Score to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Score from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Score instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Score fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence Username;
   private java.lang.CharSequence Location;
   private int Score;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Score() {}

  /**
   * All-args constructor.
   * @param Username The new value for Username
   * @param Location The new value for Location
   * @param Score The new value for Score
   */
  public Score(java.lang.CharSequence Username, java.lang.CharSequence Location, java.lang.Integer Score) {
    this.Username = Username;
    this.Location = Location;
    this.Score = Score;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Username;
    case 1: return Location;
    case 2: return Score;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Username = (java.lang.CharSequence)value$; break;
    case 1: Location = (java.lang.CharSequence)value$; break;
    case 2: Score = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Username' field.
   * @return The value of the 'Username' field.
   */
  public java.lang.CharSequence getUsername() {
    return Username;
  }


  /**
   * Sets the value of the 'Username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.CharSequence value) {
    this.Username = value;
  }

  /**
   * Gets the value of the 'Location' field.
   * @return The value of the 'Location' field.
   */
  public java.lang.CharSequence getLocation() {
    return Location;
  }


  /**
   * Sets the value of the 'Location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.Location = value;
  }

  /**
   * Gets the value of the 'Score' field.
   * @return The value of the 'Score' field.
   */
  public int getScore() {
    return Score;
  }


  /**
   * Sets the value of the 'Score' field.
   * @param value the value to set.
   */
  public void setScore(int value) {
    this.Score = value;
  }

  /**
   * Creates a new Score RecordBuilder.
   * @return A new Score RecordBuilder
   */
  public static io.confluent.developer.avro.Score.Builder newBuilder() {
    return new io.confluent.developer.avro.Score.Builder();
  }

  /**
   * Creates a new Score RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Score RecordBuilder
   */
  public static io.confluent.developer.avro.Score.Builder newBuilder(io.confluent.developer.avro.Score.Builder other) {
    if (other == null) {
      return new io.confluent.developer.avro.Score.Builder();
    } else {
      return new io.confluent.developer.avro.Score.Builder(other);
    }
  }

  /**
   * Creates a new Score RecordBuilder by copying an existing Score instance.
   * @param other The existing instance to copy.
   * @return A new Score RecordBuilder
   */
  public static io.confluent.developer.avro.Score.Builder newBuilder(io.confluent.developer.avro.Score other) {
    if (other == null) {
      return new io.confluent.developer.avro.Score.Builder();
    } else {
      return new io.confluent.developer.avro.Score.Builder(other);
    }
  }

  /**
   * RecordBuilder for Score instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Score>
    implements org.apache.avro.data.RecordBuilder<Score> {

    private java.lang.CharSequence Username;
    private java.lang.CharSequence Location;
    private int Score;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.developer.avro.Score.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Username)) {
        this.Username = data().deepCopy(fields()[0].schema(), other.Username);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Location)) {
        this.Location = data().deepCopy(fields()[1].schema(), other.Location);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Score)) {
        this.Score = data().deepCopy(fields()[2].schema(), other.Score);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Score instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.developer.avro.Score other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.Username)) {
        this.Username = data().deepCopy(fields()[0].schema(), other.Username);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Location)) {
        this.Location = data().deepCopy(fields()[1].schema(), other.Location);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Score)) {
        this.Score = data().deepCopy(fields()[2].schema(), other.Score);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'Username' field.
      * @return The value.
      */
    public java.lang.CharSequence getUsername() {
      return Username;
    }


    /**
      * Sets the value of the 'Username' field.
      * @param value The value of 'Username'.
      * @return This builder.
      */
    public io.confluent.developer.avro.Score.Builder setUsername(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Username = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Username' field has been set.
      * @return True if the 'Username' field has been set, false otherwise.
      */
    public boolean hasUsername() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Username' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.Score.Builder clearUsername() {
      Username = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Location' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocation() {
      return Location;
    }


    /**
      * Sets the value of the 'Location' field.
      * @param value The value of 'Location'.
      * @return This builder.
      */
    public io.confluent.developer.avro.Score.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Location = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Location' field has been set.
      * @return True if the 'Location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Location' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.Score.Builder clearLocation() {
      Location = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Score' field.
      * @return The value.
      */
    public int getScore() {
      return Score;
    }


    /**
      * Sets the value of the 'Score' field.
      * @param value The value of 'Score'.
      * @return This builder.
      */
    public io.confluent.developer.avro.Score.Builder setScore(int value) {
      validate(fields()[2], value);
      this.Score = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Score' field has been set.
      * @return True if the 'Score' field has been set, false otherwise.
      */
    public boolean hasScore() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Score' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.Score.Builder clearScore() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Score build() {
      try {
        Score record = new Score();
        record.Username = fieldSetFlags()[0] ? this.Username : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Location = fieldSetFlags()[1] ? this.Location : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Score = fieldSetFlags()[2] ? this.Score : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Score>
    WRITER$ = (org.apache.avro.io.DatumWriter<Score>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Score>
    READER$ = (org.apache.avro.io.DatumReader<Score>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.Username);

    out.writeString(this.Location);

    out.writeInt(this.Score);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Username = in.readString(this.Username instanceof Utf8 ? (Utf8)this.Username : null);

      this.Location = in.readString(this.Location instanceof Utf8 ? (Utf8)this.Location : null);

      this.Score = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Username = in.readString(this.Username instanceof Utf8 ? (Utf8)this.Username : null);
          break;

        case 1:
          this.Location = in.readString(this.Location instanceof Utf8 ? (Utf8)this.Location : null);
          break;

        case 2:
          this.Score = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










